-- What is the total revenue generated by the company?
SELECT
	SUM(PAYMENT_AMOUNT) AS TOTAL_REVENUE
FROM
	ORDERS;

-- What are the monthly sales and revenue trends?
SELECT
	TO_CHAR(ORDER_DATE, 'Mon YYYY') AS MONTH,
	ROUND(SUM(PAYMENT_AMOUNT), 2) AS MONTHLY_REVENUE
FROM
	ORDERS
GROUP BY
	MONTH
ORDER BY
	MONTH;

-- Which are the top 10 highest-selling products?
SELECT
	P.BOOK_TITLE,
	SUM(O.QUANTITY) AS TOTAL_SOLD
FROM
	ORDERS O
	JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.BOOK_TITLE
ORDER BY
	TOTAL_SOLD DESC
LIMIT
	10;


-- Which customers generated the highest revenue?
SELECT
	C.CUSTOMER_NAME,
	ROUND(SUM(O.PAYMENT_AMOUNT), 2) AS TOTAL_REVENUE
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	C.CUSTOMER_NAME != 'NA'
GROUP BY
	C.CUSTOMER_NAME
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	10;


-- Which product categories/genres perform the best?
SELECT
	P.GENRE,
	ROUND(SUM(O.PAYMENT_AMOUNT), 2) AS TOTAL_REVENUE
FROM
	ORDERS O
	JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.GENRE
ORDER BY
	TOTAL_REVENUE DESC;

-- What is the average order value?
SELECT
	ROUND(AVG(PAYMENT_AMOUNT), 2) AS AVG_ORDER_VALUE
FROM
	ORDERS;


-- How many orders are completed, pending, or cancelled?
SELECT
	STATUS,
	COUNT(*)
FROM
	ORDERS AS TOTAL_ORDERS
WHERE
	STATUS IN ('Pending', 'Completed', 'Cancelled')
GROUP BY
	STATUS;


--  What is the cancellation rate of orders?
SELECT
	CONCAT(COUNT(*) * 100 / 15000, '%') AS TOTAL_CANCELLATION
FROM
	ORDERS
WHERE
	STATUS = 'Cancelled';


--  Which products have the lowest stock and need restocking?
SELECT
	BOOK_TITLE,
	STOCK
FROM
	PRODUCTS
WHERE
	STOCK > 0
	AND STOCK <= 10
ORDER BY
	STOCK ASC;




--  Which customers are repeat customers?
SELECT
	CUSTOMER_ID,
	COUNT(*) AS REPEATED_ORDER
FROM
	ORDERS
GROUP BY
	CUSTOMER_ID
HAVING
	COUNT(*) = 1;


--  Which month had the highest number of orders?
SELECT 
TO_CHAR(order_date, 'Mon YYYY') AS month,
COUNT(*) AS orders
FROM orders
GROUP BY month
ORDER BY orders DESC
LIMIT 1;


--  What is the total quantity of products sold?
SELECT
	SUM(QUANTITY) AS TOTAL_PRODUCT_SOLD
FROM
	ORDERS;

-- Which products are rarely ordered?

SELECT 
p.book_title,
SUM(o.quantity) AS total_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.book_title
ORDER BY total_sold ASC
LIMIT 10;


--  What is the revenue contribution by each genre/category?
SELECT
	P.GENRE,
	SUM(PAYMENT_AMOUNT) AS TOTAL_REVENUE
FROM
	ORDERS O
	JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
	GENRE != 'NA'
GROUP BY
	P.GENRE
ORDER BY
	TOTAL_REVENUE DESC;


--  What are the top 5 most profitable products?
SELECT
	P.BOOK_TITLE,
	SUM(O.PAYMENT_AMOUNT) AS TOTAL_REVENUE
FROM
	ORDERS O
	JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.BOOK_TITLE
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	5;








